[package]
name = "breeze"
version = "0.1.0"
edition = "2021"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19.10"

[dependencies]
lalrpop-util = {version = "0.19.10", features = ["lexer"]}
regex = "1"
